#ifndef EVAPPROTOCOL_GLOBAL_H
#define EVAPPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EVAPPROTOCOL_LIBRARY)
#  define EVAPPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EVAPPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EVAPPROTOCOL_GLOBAL_H
